### ISSUE TITLE
Installation via Vundle?

### ISSUE THREAD

**Issue by maxcountryman** [daveray/vimclojure-easy#9]
I'm wondering if it's possible to install this properly via Vundle. It seems to recognize the repo but doesn't register the VimClojure commands. Any idea if there's some magic that needs to be done to get this working?

**Comment by maxcountryman** [comment]
Well it's terribly hacky but I found that if I include both VimClojure and vimclojure-easy, it does in fact work:

```
Bundle 'daveray/vimclojure-easy'
Bundle 'VimClojure'
```

**Comment by daveray** [comment]
I'm not really familiar with vundle at all. I'm guessing it assumes the repo has a particular layout, but since this is an example of a full .vim directory, it isn't quite compatible I guess. If there's a way to point Vundle at https://github.com/daveray/vimclojure-easy/tree/master/bundle/vimclojure-2.3.1, maybe that would work :)

**Comment by maxcountryman** [comment]
There may be, I have to admit I'm new to Vundle myself...I'll investigate further. :)

**Comment by maxcountryman** [comment]
Ah, there we go! You can override the runtime path like this:

```
Bundle 'daveray/vimclojure-easy', {'rtp': 'bundle/vimclojure-2.3.1'}
```

And that seems to do the trick.
